apiVersion: v1
kind: Service
metadata:
  name: ghost
  namespace: ghost-blog
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "classic"  # Use Classic Load Balancer (ELB)
spec:
  type: LoadBalancer  # This ensures AWS creates an ELB
  selector:
    app: ghost
  ports:
    - protocol: TCP
      port: 80
      targetPort: 2368  # Ghost runs on port 2368 inside the container
