apiVersion: v1
kind: PersistentVolume
metadata:
  name: ghost-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: gp3-csi  # Updated storage class
  hostPath:
    path: "/data/ghost"
